### ISSUE TITLE
How-To: Calibrate detection threshold (not required in most cases)

### ISSUE THREAD

**Issue by sinanjugbf** [Masuzu/GBFPokerBot#103] opened 2017-04-02 18:09 UTC
The pokerbot does not run for more than 5 minutes at a time and it spits this out at me:
![dwm_2017-04-02_14-06-57](https://cloud.githubusercontent.com/assets/26857048/24589758/fb96eb6a-17ad-11e7-9617-15ff3ec71080.png)
![werfault_2017-04-02_14-07-15](https://cloud.githubusercontent.com/assets/26857048/24589757/fb96f330-17ad-11e7-880e-a3a736ba5e49.png)
![werfault_2017-04-02_14-07-20](https://cloud.githubusercontent.com/assets/26857048/24589759/fb98ce30-17ad-11e7-9a39-e10c2613f9b4.png)

**Comment by po456asd** [comment] 2017-04-03 13:03
have you try reinstall vcredist already?

**Comment by sinanjugbf** [comment] 2017-04-03 16:23
I only tried repairing, but I'll try reinstalling when I get home from work.

**Comment by sinanjugbf** [comment] 2017-04-03 22:27
Reinstalled vcredist, but it still crashes the same way. It always seems to happen when the screen ends up like this http://i.imgur.com/V7FFRV0.png

**Comment by Masuzu** [comment] 2017-04-04 06:34
Hi there,

I cannot reproduce the issue.
I am afraid I will mark the ticket as invalid and close it unless you provide the console logs too as well. It's like trying to find someone in a crowd being blind.

**Comment by sinanjugbf** [comment] 2017-04-04 06:36
Does it output any log files? I can try screenshotting the console during a
crash.

**Comment by sinanjugbf** [comment] 2017-04-04 06:45
It just crashed again, here's the console, or what I can capture of it. http://i.imgur.com/BS9BTMd.png

**Comment by Masuzu** [comment] 2017-04-04 09:05
Oh that makes sense, this is not a crash in this case.
Please try and lower the parameter "HigherOrLowerDetectionThreshold" to 0.8.
Same thing with the "DetectionThreshold" should you have the same kind of messages outside of the higher or lower phase. As you can see the detection threshold is set to 0.85 by default but in your case it fails due to slightly lower scores (0.83XXX) as shown in your screenshot.

**Comment by sinanjugbf** [comment] 2017-04-04 16:44
Okay, I'll give this a shot.

**Comment by sinanjugbf** [comment] 2017-04-04 17:56
It's still crashing, here's the log: http://i.imgur.com/5arnwdg.png

**Comment by Masuzu** [comment] 2017-04-04 18:46
Ah so what happens is that the clicks are not registered or else:
- you are experiencing severe lags
- have a poor internet connection (lags) - I have on my Youtube channel some videos showcasing how lags severely degrade the performance of the bot/make it unusable
- use a low end computer
- a combinations of one or several of aforementioned factors
Your case may unfortunately fall in the minority of the user base which can't use the bot in the optimal conditions with their computer setup, in which unfortunately I won't do anything to fix this as it the bot is not supposed to be used under these conditions.

**Comment by sinanjugbf** [comment] 2017-04-04 22:59
I think I fixed it actually. Hardware acceleration was turned off in chrome. I turned it on and it has been running for an hour or so without crashing.

**Comment by Masuzu** [comment] 2017-04-05 17:55
Ah alright, this can cause a severe FPS drop indeed. Nicely spotted!

**Closed by Masuzu** 2017-04-05 17:55 UTC
Labels: help wanted, question

**Comment by Masuzu** [comment] 2017-04-06 16:13
Linking https://github.com/Masuzu/GBFPokerBot/issues/105 as there was a bug indeed which caused the reported crash.
This will be fixed in the upcoming version.
